# Force npm instead of yarn
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["rm -f yarn.lock", "npm install --legacy-peer-deps"]

[phases.build]
cmds = ["CI=false npm run build"]

[start]
cmd = "npx serve -s build -l $PORT"
